[package]
name = "shuttle-template-yew-server"
version = "2.47.0"
edition = "2021"
description = "Template frontend app using the Yew web framework for Rust"
readme = "README.md"
authors = ["Jeffery D. Mitchell", "<crusty-rustacean@jeffmitchelldev.com>"]
repository = "https://github.com/sentinel1909/shuttle-template-yew"
license = 'MIT'
publish = false

[dependencies]
rocket = "0.5.1"
shuttle-rocket = "0.47.0"
shuttle-runtime = "0.47.0"
